begin;

create table if not exists public.app_users (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(160) not null,
  password_hash varchar(255) not null,
  role varchar(30) not null default 'OPERATOR',
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  constraint app_users_role_check check (role in ('OPERATOR'))
);

create unique index if not exists app_users_email_unique_idx
  on public.app_users (lower(email));

create unique index if not exists app_users_single_active_operator_idx
  on public.app_users (role)
  where role = 'OPERATOR' and active is true;

commit;
